#!/usr/bin/env Rscript

suppressPackageStartupMessages({
  library(readr)
  library(dplyr)
  library(ggplot2)
  library(stringr)
  library(tidyr)
})

# =========================================================
# Compact matrix visualization for selected existing GO terms.
#
# Input:
#   1) config/existing_go_plot_config.tsv
#   2) results/plots/*_PFC_vs_MCX_GO_bias_dotplot_data.tsv
#      generated by plot_existing_region_go_dotplot.R
#
# Output:
#   - a merged long table
#   - compact PDF/PNG matrix plot
#
# Visual encoding:
#   x     = Region (MCX/PFC)
#   y     = selected GO term
#   facet = subtype/contrast and direction (up/down)
#   color = signed -log10(adjusted P)
#           red: up; blue: down
#   size  = GeneRatio
# =========================================================

parse_args_simple <- function() {
  args <- commandArgs(trailingOnly = TRUE)
  out <- list()
  i <- 1
  while (i <= length(args)) {
    key <- args[i]
    if (startsWith(key, "--")) {
      key2 <- sub("^--", "", key)
      if (i == length(args) || startsWith(args[i + 1], "--")) {
        out[[key2]] <- TRUE
        i <- i + 1
      } else {
        out[[key2]] <- args[i + 1]
        i <- i + 2
      }
    } else {
      i <- i + 1
    }
  }
  out
}

opt <- parse_args_simple()
required_args <- c("config", "input-dir", "out-prefix")
missing_args <- required_args[!required_args %in% names(opt)]
if (length(missing_args) > 0) {
  stop("Missing required arguments: ", paste(missing_args, collapse = ", "))
}

config_fp <- opt[["config"]]
input_dir <- opt[["input-dir"]]
out_prefix <- opt[["out-prefix"]]
width <- ifelse("width" %in% names(opt), as.numeric(opt[["width"]]), 15)
height <- ifelse("height" %in% names(opt), as.numeric(opt[["height"]]), 10)
max_terms_per_panel <- ifelse("max-terms-per-panel" %in% names(opt), as.integer(opt[["max-terms-per-panel"]]), 12)

out_dir <- dirname(out_prefix)
dir.create(out_dir, recursive = TRUE, showWarnings = FALSE)

make_term_label <- function(x, width = 30) {
  x <- as.character(x)
  x <- str_replace_all(x, "_", " ")
  x <- str_to_sentence(x)
  str_wrap(x, width = width)
}

parse_gene_ratio <- function(x) {
  out <- sapply(x, function(z) {
    if (is.na(z)) return(NA_real_)
    z <- as.character(z)
    if (grepl("/", z, fixed = TRUE)) {
      a <- strsplit(z, "/", fixed = TRUE)[[1]]
      if (length(a) != 2) return(NA_real_)
      num <- suppressWarnings(as.numeric(a[1]))
      den <- suppressWarnings(as.numeric(a[2]))
      if (is.na(num) || is.na(den) || den == 0) return(NA_real_)
      return(num / den)
    }
    zz <- suppressWarnings(as.numeric(z))
    if (!is.na(zz)) return(zz)
    return(NA_real_)
  })
  as.numeric(out)
}

cfg <- readr::read_tsv(
  config_fp,
  show_col_types = FALSE,
  col_types = readr::cols(.default = readr::col_character())
) %>%
  mutate(
    contrast = trimws(.data$contrast),
    short_label = ifelse(is.na(.data$short_label) | trimws(.data$short_label) == "", .data$contrast, .data$short_label),
    phenotype_region_bias = ifelse(is.na(.data$phenotype_region_bias), "", .data$phenotype_region_bias)
  )

if (!"contrast" %in% colnames(cfg)) stop("Config must contain column: contrast")

read_one_selected <- function(contrast) {
  fp <- file.path(input_dir, paste0(contrast, "_PFC_vs_MCX_GO_bias_dotplot_data.tsv"))
  if (!file.exists(fp)) {
    message("[warn] Missing selected GO table: ", fp)
    return(data.frame())
  }
  if (file.info(fp)$size == 0) {
    message("[warn] Empty selected GO table: ", fp)
    return(data.frame())
  }
  x <- suppressMessages(readr::read_tsv(fp, show_col_types = FALSE))
  if (nrow(x) == 0) return(data.frame())
  x$contrast <- contrast
  x$selected_table <- fp
  x
}

all_selected <- bind_rows(lapply(cfg$contrast, read_one_selected))

if (nrow(all_selected) == 0) {
  stop("No selected GO dotplot data found in input-dir: ", input_dir)
}

required_cols <- c("Description", "p.adjust", "GeneRatio", "Region", "direction_raw", "contrast")
missing_cols <- setdiff(required_cols, colnames(all_selected))
if (length(missing_cols) > 0) {
  stop("Merged selected tables missing columns: ", paste(missing_cols, collapse = ", "))
}

plot_df <- all_selected %>%
  left_join(cfg %>% select(.data$contrast, .data$short_label, .data$phenotype_region_bias), by = "contrast") %>%
  mutate(
    Description = as.character(.data$Description),
    p.adjust = suppressWarnings(as.numeric(.data$p.adjust)),
    GeneRatio = as.character(.data$GeneRatio),
    GeneRatio_num = if ("GeneRatio_num" %in% colnames(.)) suppressWarnings(as.numeric(.data$GeneRatio_num)) else parse_gene_ratio(.data$GeneRatio),
    log10_padj = -log10(pmax(.data$p.adjust, .Machine$double.xmin)),
    signed_log10_padj = ifelse(.data$direction_raw == "up", .data$log10_padj, -.data$log10_padj),
    term_show = make_term_label(.data$Description),
    Region = factor(.data$Region, levels = c("MCX", "PFC")),
    direction_raw = factor(.data$direction_raw, levels = c("down", "up")),
    facet_label = paste0(.data$short_label, "\n", as.character(.data$direction_raw)),
    facet_label = factor(
      .data$facet_label,
      levels = as.vector(t(outer(cfg$short_label, c("down", "up"), paste, sep = "\n")))
    )
  ) %>%
  filter(!is.na(.data$p.adjust), !is.na(.data$Region), !is.na(.data$direction_raw))

if (all(is.na(plot_df$GeneRatio_num))) {
  message("[warn] All GeneRatio_num are NA. Using fixed point size.")
  plot_df$GeneRatio_num <- 0.05
}
plot_df$GeneRatio_num[is.na(plot_df$GeneRatio_num)] <- median(plot_df$GeneRatio_num, na.rm = TRUE)

# Keep the strongest rows if a panel is too dense.
plot_df <- plot_df %>%
  group_by(.data$contrast, .data$direction_raw, .data$Description) %>%
  mutate(term_strength = max(.data$log10_padj, na.rm = TRUE)) %>%
  ungroup() %>%
  group_by(.data$contrast, .data$direction_raw) %>%
  mutate(term_rank = dense_rank(desc(.data$term_strength))) %>%
  ungroup() %>%
  filter(.data$term_rank <= max_terms_per_panel)

# Order terms within each facet by direction and strongest significance.
term_levels <- plot_df %>%
  distinct(.data$facet_label, .data$term_show, .data$term_strength) %>%
  arrange(.data$facet_label, .data$term_strength) %>%
  pull(.data$term_show) %>%
  unique()
plot_df$term_show <- factor(plot_df$term_show, levels = term_levels)

# Save merged long table.
readr::write_tsv(plot_df, paste0(out_prefix, ".selected_GO_long.tsv"))

p <- ggplot(plot_df, aes(x = .data$Region, y = .data$term_show)) +
  geom_point(aes(size = .data$GeneRatio_num, color = .data$signed_log10_padj), alpha = 0.90) +
  facet_wrap(~facet_label, scales = "free_y", nrow = 2) +
  scale_color_gradient2(
    low = "#2166AC",
    mid = "grey90",
    high = "#B2182B",
    midpoint = 0,
    name = "Signed -log10(FDR)\nblue=down, red=up"
  ) +
  scale_size_continuous(name = "GeneRatio", range = c(1.8, 6.5)) +
  labs(
    x = NULL,
    y = NULL,
    title = NULL
  ) +
  theme_bw(base_size = 11) +
  theme(
    strip.background = element_rect(fill = "grey92", color = "black"),
    strip.text = element_text(face = "bold", size = 9),
    axis.text.x = element_text(face = "bold", color = "black"),
    axis.text.y = element_text(color = "black", size = 8),
    panel.grid.major = element_line(color = "grey88", linewidth = 0.25),
    panel.grid.minor = element_blank(),
    legend.position = "right",
    plot.title = element_text(face = "bold", hjust = 0.5)
  )

ggsave(paste0(out_prefix, ".pdf"), plot = p, width = width, height = height, limitsize = FALSE)
ggsave(paste0(out_prefix, ".png"), plot = p, width = width, height = height, dpi = 300, limitsize = FALSE)

message("[done] Saved:")
message("  ", paste0(out_prefix, ".pdf"))
message("  ", paste0(out_prefix, ".png"))
message("  ", paste0(out_prefix, ".selected_GO_long.tsv"))
